"""Launch the persistent Gemini Chrome session used by MicroGen on Dell-115.

Default mode never asks for a Google username/password. It reuses the persistent
MicroGen Chrome profile. Alternate-user mode uses a separate persistent profile
and leaves authentication entirely to the user in Chrome.
"""
from __future__ import annotations
import argparse
import os
import re
import socket
import subprocess
import time
import urllib.request
from pathlib import Path

GEMINI_URL = "https://gemini.google.com/app"
DEFAULT_PORT = 9222
ALT_PORT = 9223


def chrome_exe() -> str:
    override = os.getenv("CHROME_EXE")
    candidates = [override,
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]
    for item in candidates:
        if item and Path(item).is_file():
            return item
    raise FileNotFoundError("Google Chrome not found; set CHROME_EXE")


def profile_root(alternate_user: str | None) -> Path:
    local = Path(os.getenv("LOCALAPPDATA", str(Path.home() / "AppData" / "Local")))
    if alternate_user is None:
        # Reuse the exact persistent profile created by template_v2 on Dell-115.
        # It is expected to contain the existing authorized Gemini login.
        hostname = socket.gethostname().replace(" ", "_")
        return local / f"gemini_automation_{hostname}"
    # Label only: never treated as a credential or typed into Google's login form.
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", alternate_user).strip("._") or "alternate"
    return local / "MicroGen_AI_Web" / "gemini_alternate" / safe


def ready(port: int) -> bool:
    try:
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/json/version", timeout=1.5) as r:
            return r.status == 200
    except Exception:
        return False


def wait_ready(port: int, timeout: int = 20) -> bool:
    end = time.time() + timeout
    while time.time() < end:
        if ready(port):
            return True
        time.sleep(.5)
    return False


def launch(alternate_user: str | None = None, port: int | None = None) -> tuple[int, Path]:
    port = port or (ALT_PORT if alternate_user else DEFAULT_PORT)
    profile = profile_root(alternate_user)
    if ready(port):
        print(f"[gemini] reusing active debug session on port {port}")
        return port, profile
    profile.mkdir(parents=True, exist_ok=True)
    args = [chrome_exe(), f"--remote-debugging-port={port}", f"--user-data-dir={profile}",
            "--no-first-run", "--no-default-browser-check", GEMINI_URL]
    subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not wait_ready(port):
        raise RuntimeError(f"Chrome did not expose DevTools on port {port}")
    if alternate_user:
        print(f"[gemini] alternate-user profile '{alternate_user}' opened.")
        print("[gemini] Sign in interactively in Chrome if this profile is not already authenticated.")
        print("[gemini] MicroGen does not request, type, capture, or store your Google password.")
    else:
        print("[gemini] default persistent MicroGen profile opened.")
        print("[gemini] No login prompt is generated by MicroGen; the existing Gemini session is reused.")
        print("[gemini] If this profile has never been authenticated, sign in once manually in Chrome.")
    return port, profile


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Launch MicroGen's persistent Gemini Chrome profile")
    parser.add_argument("--alternate-user", metavar="PROFILE_LABEL",
                        help="Explicitly use a separate persistent Chrome profile; login is manual if needed")
    parser.add_argument("--port", type=int)
    args = parser.parse_args(argv)
    launch(args.alternate_user, args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
